/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */
package com.hyg.dao;

import java.sql.SQLException;
import java.util.List;
import java.util.Map;


/**
 * @author 黑猴子的家
 * @博客 https://www.jianshu.com/u/37fd8e2dff4c
 * @官网 http://www.121ugrow.com/
 */
public interface ReportDaoI
{
	
	public List<Map<String, Object>> findMonthInstock(String sql,Object[] param) throws SQLException;
	
	public List<Map<String, Object>> findMonthOutstock(String sql,Object[] param) throws SQLException;
	

}
