/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class KInstock implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_INSTOCK table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column INSTOCKNO in the K_INSTOCK table.
	 */
	protected String instockno;

	/** 
	 * This attribute maps to the column STOCKID in the K_INSTOCK table.
	 */
	protected BigDecimal stockid;

	/** 
	 * This attribute maps to the column SUPPLIERID in the K_INSTOCK table.
	 */
	protected BigDecimal supplierid;

	/** 
	 * This attribute maps to the column INSTOCKSTATE in the K_INSTOCK table.
	 */
	protected String instockstate;

	/** 
	 * This attribute maps to the column INSTOCKDATE in the K_INSTOCK table.
	 */
	protected Date instockdate;

	/** 
	 * This attribute maps to the column REMARK in the K_INSTOCK table.
	 */
	protected String remark;

	public BigDecimal getId() {
		return id;
	}

	public void setId(BigDecimal id) {
		this.id = id;
	}

	public String getInstockno() {
		return instockno;
	}

	public void setInstockno(String instockno) {
		this.instockno = instockno;
	}

	public BigDecimal getStockid() {
		return stockid;
	}

	public void setStockid(BigDecimal stockid) {
		this.stockid = stockid;
	}

	public BigDecimal getSupplierid() {
		return supplierid;
	}

	public void setSupplierid(BigDecimal supplierid) {
		this.supplierid = supplierid;
	}

	public String getInstockstate() {
		return instockstate;
	}

	public void setInstockstate(String instockstate) {
		this.instockstate = instockstate;
	}

	public Date getInstockdate() {
		return instockdate;
	}

	public void setInstockdate(Date instockdate) {
		this.instockdate = instockdate;
	}

	public String getRemark() {
		return remark;
	}

	public void setRemark(String remark) {
		this.remark = remark;
	}

	public KInstock(BigDecimal id, String instockno, BigDecimal stockid,
			BigDecimal supplierid, String instockstate, Date instockdate,
			String remark) {
		super();
		this.id = id;
		this.instockno = instockno;
		this.stockid = stockid;
		this.supplierid = supplierid;
		this.instockstate = instockstate;
		this.instockdate = instockdate;
		this.remark = remark;
	}

	public KInstock() {
		super();
	}

}
