/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class KInventory implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_INVENTORY table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column STOCKID in the K_INVENTORY table.
	 */
	protected BigDecimal stockid;

	/** 
	 * This attribute maps to the column PRODUCTNO in the K_INVENTORY table.
	 */
	protected String productno;

	/** 
	 * This attribute maps to the column PRODUCTNAME in the K_INVENTORY table.
	 */
	protected String productname;

	/** 
	 * This attribute maps to the column PRODUCTSTANDARD in the K_INVENTORY table.
	 */
	protected String productstandard;

	/** 
	 * This attribute maps to the column INVENTORYNUM in the K_INVENTORY table.
	 */
	protected BigDecimal inventorynum;

	/** 
	 * This attribute maps to the column INVENTORYPRICE in the K_INVENTORY table.
	 */
	protected BigDecimal inventoryprice;

	/** 
	 * This attribute maps to the column INSTOCKNUM in the K_INVENTORY table.
	 */
	protected BigDecimal instocknum;

	/** 
	 * This attribute maps to the column INSTOCKPRICE in the K_INVENTORY table.
	 */
	protected BigDecimal instockprice;

	/** 
	 * This attribute maps to the column OUTSTOCKNUM in the K_INVENTORY table.
	 */
	protected BigDecimal outstocknum;

	/** 
	 * This attribute maps to the column OUTSTOCKPRICE in the K_INVENTORY table.
	 */
	protected BigDecimal outstockprice;

	/** 
	 * This attribute maps to the column MAXNUM in the K_INVENTORY table.
	 */
	protected BigDecimal maxnum;

	/** 
	 * This attribute maps to the column MINNUM in the K_INVENTORY table.
	 */
	protected BigDecimal minnum;

	/** 
	 * This attribute maps to the column REMARK in the K_INVENTORY table.
	 */
	protected String remark;

	/**
	 * Method 'KInventory'
	 * 
	 */
	public KInventory()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getStockid'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getStockid()
	{
		return stockid;
	}

	/**
	 * Method 'setStockid'
	 * 
	 * @param stockid
	 */
	public void setStockid(BigDecimal stockid)
	{
		this.stockid = stockid;
	}

	/**
	 * Method 'getProductno'
	 * 
	 * @return String
	 */
	public String getProductno()
	{
		return productno;
	}

	/**
	 * Method 'setProductno'
	 * 
	 * @param productno
	 */
	public void setProductno(String productno)
	{
		this.productno = productno;
	}

	/**
	 * Method 'getProductname'
	 * 
	 * @return String
	 */
	public String getProductname()
	{
		return productname;
	}

	/**
	 * Method 'setProductname'
	 * 
	 * @param productname
	 */
	public void setProductname(String productname)
	{
		this.productname = productname;
	}

	/**
	 * Method 'getProductstandard'
	 * 
	 * @return String
	 */
	public String getProductstandard()
	{
		return productstandard;
	}

	/**
	 * Method 'setProductstandard'
	 * 
	 * @param productstandard
	 */
	public void setProductstandard(String productstandard)
	{
		this.productstandard = productstandard;
	}

	/**
	 * Method 'getInventorynum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getInventorynum()
	{
		return inventorynum;
	}

	/**
	 * Method 'setInventorynum'
	 * 
	 * @param inventorynum
	 */
	public void setInventorynum(BigDecimal inventorynum)
	{
		this.inventorynum = inventorynum;
	}

	/**
	 * Method 'getInventoryprice'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getInventoryprice()
	{
		return inventoryprice;
	}

	/**
	 * Method 'setInventoryprice'
	 * 
	 * @param inventoryprice
	 */
	public void setInventoryprice(BigDecimal inventoryprice)
	{
		this.inventoryprice = inventoryprice;
	}

	/**
	 * Method 'getInstocknum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getInstocknum()
	{
		return instocknum;
	}

	/**
	 * Method 'setInstocknum'
	 * 
	 * @param instocknum
	 */
	public void setInstocknum(BigDecimal instocknum)
	{
		this.instocknum = instocknum;
	}

	/**
	 * Method 'getInstockprice'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getInstockprice()
	{
		return instockprice;
	}

	/**
	 * Method 'setInstockprice'
	 * 
	 * @param instockprice
	 */
	public void setInstockprice(BigDecimal instockprice)
	{
		this.instockprice = instockprice;
	}

	/**
	 * Method 'getOutstocknum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getOutstocknum()
	{
		return outstocknum;
	}

	/**
	 * Method 'setOutstocknum'
	 * 
	 * @param outstocknum
	 */
	public void setOutstocknum(BigDecimal outstocknum)
	{
		this.outstocknum = outstocknum;
	}

	/**
	 * Method 'getOutstockprice'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getOutstockprice()
	{
		return outstockprice;
	}

	/**
	 * Method 'setOutstockprice'
	 * 
	 * @param outstockprice
	 */
	public void setOutstockprice(BigDecimal outstockprice)
	{
		this.outstockprice = outstockprice;
	}

	/**
	 * Method 'getMaxnum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getMaxnum()
	{
		return maxnum;
	}

	/**
	 * Method 'setMaxnum'
	 * 
	 * @param maxnum
	 */
	public void setMaxnum(BigDecimal maxnum)
	{
		this.maxnum = maxnum;
	}

	/**
	 * Method 'getMinnum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getMinnum()
	{
		return minnum;
	}

	/**
	 * Method 'setMinnum'
	 * 
	 * @param minnum
	 */
	public void setMinnum(BigDecimal minnum)
	{
		this.minnum = minnum;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KInventory)) {
			return false;
		}
		
		final KInventory _cast = (KInventory) _other;
		if (id != _cast.id) {
			return false;
		}
		
		if (stockid == null ? _cast.stockid != stockid : !stockid.equals( _cast.stockid )) {
			return false;
		}
		
		if (productno == null ? _cast.productno != productno : !productno.equals( _cast.productno )) {
			return false;
		}
		
		if (productname == null ? _cast.productname != productname : !productname.equals( _cast.productname )) {
			return false;
		}
		
		if (productstandard == null ? _cast.productstandard != productstandard : !productstandard.equals( _cast.productstandard )) {
			return false;
		}
		
		if (inventorynum == null ? _cast.inventorynum != inventorynum : !inventorynum.equals( _cast.inventorynum )) {
			return false;
		}
		
		if (inventoryprice == null ? _cast.inventoryprice != inventoryprice : !inventoryprice.equals( _cast.inventoryprice )) {
			return false;
		}
		
		if (instocknum == null ? _cast.instocknum != instocknum : !instocknum.equals( _cast.instocknum )) {
			return false;
		}
		
		if (instockprice == null ? _cast.instockprice != instockprice : !instockprice.equals( _cast.instockprice )) {
			return false;
		}
		
		if (outstocknum == null ? _cast.outstocknum != outstocknum : !outstocknum.equals( _cast.outstocknum )) {
			return false;
		}
		
		if (outstockprice == null ? _cast.outstockprice != outstockprice : !outstockprice.equals( _cast.outstockprice )) {
			return false;
		}
		
		if (maxnum == null ? _cast.maxnum != maxnum : !maxnum.equals( _cast.maxnum )) {
			return false;
		}
		
		if (minnum == null ? _cast.minnum != minnum : !minnum.equals( _cast.minnum )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		_hashCode = 29 * _hashCode + id.hashCode();
		if (stockid != null) {
			_hashCode = 29 * _hashCode + stockid.hashCode();
		}
		
		if (productno != null) {
			_hashCode = 29 * _hashCode + productno.hashCode();
		}
		
		if (productname != null) {
			_hashCode = 29 * _hashCode + productname.hashCode();
		}
		
		if (productstandard != null) {
			_hashCode = 29 * _hashCode + productstandard.hashCode();
		}
		
		if (inventorynum != null) {
			_hashCode = 29 * _hashCode + inventorynum.hashCode();
		}
		
		if (inventoryprice != null) {
			_hashCode = 29 * _hashCode + inventoryprice.hashCode();
		}
		
		if (instocknum != null) {
			_hashCode = 29 * _hashCode + instocknum.hashCode();
		}
		
		if (instockprice != null) {
			_hashCode = 29 * _hashCode + instockprice.hashCode();
		}
		
		if (outstocknum != null) {
			_hashCode = 29 * _hashCode + outstocknum.hashCode();
		}
		
		if (outstockprice != null) {
			_hashCode = 29 * _hashCode + outstockprice.hashCode();
		}
		
		if (maxnum != null) {
			_hashCode = 29 * _hashCode + maxnum.hashCode();
		}
		
		if (minnum != null) {
			_hashCode = 29 * _hashCode + minnum.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}


	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.KInventory: " );
		ret.append( "id=" + id );
		ret.append( ", stockid=" + stockid );
		ret.append( ", productno=" + productno );
		ret.append( ", productname=" + productname );
		ret.append( ", productstandard=" + productstandard );
		ret.append( ", inventorynum=" + inventorynum );
		ret.append( ", inventoryprice=" + inventoryprice );
		ret.append( ", instocknum=" + instocknum );
		ret.append( ", instockprice=" + instockprice );
		ret.append( ", outstocknum=" + outstocknum );
		ret.append( ", outstockprice=" + outstockprice );
		ret.append( ", maxnum=" + maxnum );
		ret.append( ", minnum=" + minnum );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
