/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class KOutstock implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_OUTSTOCK table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column OUTSTOCKNO in the K_OUTSTOCK table.
	 */
	protected String outstockno;

	/** 
	 * This attribute maps to the column STOCKID in the K_OUTSTOCK table.
	 */
	protected BigDecimal stockid;

	/** 
	 * This attribute maps to the column SUPPLIERID in the K_OUTSTOCK table.
	 */
	protected BigDecimal supplierid;

	/** 
	 * This attribute maps to the column OUTSTOCKSTATE in the K_OUTSTOCK table.
	 */
	protected String outstockstate;

	/** 
	 * This attribute maps to the column OUTSTOCKDATE in the K_OUTSTOCK table.
	 */
	protected Date outstockdate;

	/** 
	 * This attribute maps to the column REMARK in the K_OUTSTOCK table.
	 */
	protected String remark;

	/**
	 * Method 'KOutstock'
	 * 
	 */
	public KOutstock()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getOutstockno'
	 * 
	 * @return String
	 */
	public String getOutstockno()
	{
		return outstockno;
	}

	/**
	 * Method 'setOutstockno'
	 * 
	 * @param outstockno
	 */
	public void setOutstockno(String outstockno)
	{
		this.outstockno = outstockno;
	}

	/**
	 * Method 'getStockid'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getStockid()
	{
		return stockid;
	}

	/**
	 * Method 'setStockid'
	 * 
	 * @param stockid
	 */
	public void setStockid(BigDecimal stockid)
	{
		this.stockid = stockid;
	}

	/**
	 * Method 'getSupplierid'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getSupplierid()
	{
		return supplierid;
	}

	/**
	 * Method 'setSupplierid'
	 * 
	 * @param supplierid
	 */
	public void setSupplierid(BigDecimal supplierid)
	{
		this.supplierid = supplierid;
	}

	/**
	 * Method 'getOutstockstate'
	 * 
	 * @return String
	 */
	public String getOutstockstate()
	{
		return outstockstate;
	}

	/**
	 * Method 'setOutstockstate'
	 * 
	 * @param outstockstate
	 */
	public void setOutstockstate(String outstockstate)
	{
		this.outstockstate = outstockstate;
	}

	/**
	 * Method 'getOutstockdate'
	 * 
	 * @return Date
	 */
	public Date getOutstockdate()
	{
		return outstockdate;
	}

	/**
	 * Method 'setOutstockdate'
	 * 
	 * @param outstockdate
	 */
	public void setOutstockdate(Date outstockdate)
	{
		this.outstockdate = outstockdate;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KOutstock)) {
			return false;
		}
		
		final KOutstock _cast = (KOutstock) _other;
		if (id == null ? _cast.id != id : !id.equals( _cast.id )) {
			return false;
		}
		
		if (outstockno == null ? _cast.outstockno != outstockno : !outstockno.equals( _cast.outstockno )) {
			return false;
		}
		
		if (stockid == null ? _cast.stockid != stockid : !stockid.equals( _cast.stockid )) {
			return false;
		}
		
		if (supplierid == null ? _cast.supplierid != supplierid : !supplierid.equals( _cast.supplierid )) {
			return false;
		}
		
		if (outstockstate == null ? _cast.outstockstate != outstockstate : !outstockstate.equals( _cast.outstockstate )) {
			return false;
		}
		
		if (outstockdate == null ? _cast.outstockdate != outstockdate : !outstockdate.equals( _cast.outstockdate )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (id != null) {
			_hashCode = 29 * _hashCode + id.hashCode();
		}
		
		if (outstockno != null) {
			_hashCode = 29 * _hashCode + outstockno.hashCode();
		}
		
		if (stockid != null) {
			_hashCode = 29 * _hashCode + stockid.hashCode();
		}
		
		if (supplierid != null) {
			_hashCode = 29 * _hashCode + supplierid.hashCode();
		}
		
		if (outstockstate != null) {
			_hashCode = 29 * _hashCode + outstockstate.hashCode();
		}
		
		if (outstockdate != null) {
			_hashCode = 29 * _hashCode + outstockdate.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}


	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.KOutstock: " );
		ret.append( "id=" + id );
		ret.append( ", outstockno=" + outstockno );
		ret.append( ", stockid=" + stockid );
		ret.append( ", supplierid=" + supplierid );
		ret.append( ", outstockstate=" + outstockstate );
		ret.append( ", outstockdate=" + outstockdate );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
