/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class KOutstockDetail implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_OUTSTOCK_DETAIL table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column OUTSTOCKID in the K_OUTSTOCK_DETAIL table.
	 */
	protected BigDecimal outstockid;

	/** 
	 * This attribute maps to the column PRODUCTNO in the K_OUTSTOCK_DETAIL table.
	 */
	protected String productno;

	/** 
	 * This attribute maps to the column PRODUCTNAME in the K_OUTSTOCK_DETAIL table.
	 */
	protected String productname;

	/** 
	 * This attribute maps to the column PRODUCTSTANDARD in the K_OUTSTOCK_DETAIL table.
	 */
	protected String productstandard;

	/** 
	 * This attribute maps to the column PRODUCTNUM in the K_OUTSTOCK_DETAIL table.
	 */
	protected BigDecimal productnum;

	/** 
	 * This attribute maps to the column UNIT in the K_OUTSTOCK_DETAIL table.
	 */
	protected String unit;

	/** 
	 * This attribute maps to the column PRICE in the K_OUTSTOCK_DETAIL table.
	 */
	protected BigDecimal price;

	/** 
	 * This attribute maps to the column TOTALPRICE in the K_OUTSTOCK_DETAIL table.
	 */
	protected BigDecimal totalprice;

	/** 
	 * This attribute maps to the column REMARK in the K_OUTSTOCK_DETAIL table.
	 */
	protected String remark;

	/**
	 * Method 'KOutstockDetail'
	 * 
	 */
	public KOutstockDetail()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getOutstockid'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getOutstockid()
	{
		return outstockid;
	}

	/**
	 * Method 'setOutstockid'
	 * 
	 * @param outstockid
	 */
	public void setOutstockid(BigDecimal outstockid)
	{
		this.outstockid = outstockid;
	}

	/**
	 * Method 'getProductno'
	 * 
	 * @return String
	 */
	public String getProductno()
	{
		return productno;
	}

	/**
	 * Method 'setProductno'
	 * 
	 * @param productno
	 */
	public void setProductno(String productno)
	{
		this.productno = productno;
	}

	/**
	 * Method 'getProductname'
	 * 
	 * @return String
	 */
	public String getProductname()
	{
		return productname;
	}

	/**
	 * Method 'setProductname'
	 * 
	 * @param productname
	 */
	public void setProductname(String productname)
	{
		this.productname = productname;
	}

	/**
	 * Method 'getProductstandard'
	 * 
	 * @return String
	 */
	public String getProductstandard()
	{
		return productstandard;
	}

	/**
	 * Method 'setProductstandard'
	 * 
	 * @param productstandard
	 */
	public void setProductstandard(String productstandard)
	{
		this.productstandard = productstandard;
	}

	/**
	 * Method 'getProductnum'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getProductnum()
	{
		return productnum;
	}

	/**
	 * Method 'setProductnum'
	 * 
	 * @param productnum
	 */
	public void setProductnum(BigDecimal productnum)
	{
		this.productnum = productnum;
	}

	/**
	 * Method 'getUnit'
	 * 
	 * @return String
	 */
	public String getUnit()
	{
		return unit;
	}

	/**
	 * Method 'setUnit'
	 * 
	 * @param unit
	 */
	public void setUnit(String unit)
	{
		this.unit = unit;
	}

	/**
	 * Method 'getPrice'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getPrice()
	{
		return price;
	}

	/**
	 * Method 'setPrice'
	 * 
	 * @param price
	 */
	public void setPrice(BigDecimal price)
	{
		this.price = price;
	}

	/**
	 * Method 'getTotalprice'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getTotalprice()
	{
		return totalprice;
	}

	/**
	 * Method 'setTotalprice'
	 * 
	 * @param totalprice
	 */
	public void setTotalprice(BigDecimal totalprice)
	{
		this.totalprice = totalprice;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KOutstockDetail)) {
			return false;
		}
		
		final KOutstockDetail _cast = (KOutstockDetail) _other;
		if (id == null ? _cast.id != id : !id.equals( _cast.id )) {
			return false;
		}
		
		if (outstockid == null ? _cast.outstockid != outstockid : !outstockid.equals( _cast.outstockid )) {
			return false;
		}
		
		if (productno == null ? _cast.productno != productno : !productno.equals( _cast.productno )) {
			return false;
		}
		
		if (productname == null ? _cast.productname != productname : !productname.equals( _cast.productname )) {
			return false;
		}
		
		if (productstandard == null ? _cast.productstandard != productstandard : !productstandard.equals( _cast.productstandard )) {
			return false;
		}
		
		if (productnum == null ? _cast.productnum != productnum : !productnum.equals( _cast.productnum )) {
			return false;
		}
		
		if (unit == null ? _cast.unit != unit : !unit.equals( _cast.unit )) {
			return false;
		}
		
		if (price == null ? _cast.price != price : !price.equals( _cast.price )) {
			return false;
		}
		
		if (totalprice == null ? _cast.totalprice != totalprice : !totalprice.equals( _cast.totalprice )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (id != null) {
			_hashCode = 29 * _hashCode + id.hashCode();
		}
		
		if (outstockid != null) {
			_hashCode = 29 * _hashCode + outstockid.hashCode();
		}
		
		if (productno != null) {
			_hashCode = 29 * _hashCode + productno.hashCode();
		}
		
		if (productname != null) {
			_hashCode = 29 * _hashCode + productname.hashCode();
		}
		
		if (productstandard != null) {
			_hashCode = 29 * _hashCode + productstandard.hashCode();
		}
		
		if (productnum != null) {
			_hashCode = 29 * _hashCode + productnum.hashCode();
		}
		
		if (unit != null) {
			_hashCode = 29 * _hashCode + unit.hashCode();
		}
		
		if (price != null) {
			_hashCode = 29 * _hashCode + price.hashCode();
		}
		
		if (totalprice != null) {
			_hashCode = 29 * _hashCode + totalprice.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}


	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.KOutstockDetail: " );
		ret.append( "id=" + id );
		ret.append( ", outstockid=" + outstockid );
		ret.append( ", productno=" + productno );
		ret.append( ", productname=" + productname );
		ret.append( ", productstandard=" + productstandard );
		ret.append( ", productnum=" + productnum );
		ret.append( ", unit=" + unit );
		ret.append( ", price=" + price );
		ret.append( ", totalprice=" + totalprice );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
