/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class KSupplier implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_SUPPLIER table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column SUPPLIERNO in the K_SUPPLIER table.
	 */
	protected String supplierno;

	/** 
	 * This attribute maps to the column SUPPLIERNAME in the K_SUPPLIER table.
	 */
	protected String suppliername;

	/** 
	 * This attribute maps to the column PROVINCECODE in the K_SUPPLIER table.
	 */
	protected String provincecode;

	/** 
	 * This attribute maps to the column SUPPLIERADDRESS in the K_SUPPLIER table.
	 */
	protected String supplieraddress;

	/** 
	 * This attribute maps to the column SUPPLIEREMAIL in the K_SUPPLIER table.
	 */
	protected String supplieremail;

	/** 
	 * This attribute maps to the column SUPPLIERTEL in the K_SUPPLIER table.
	 */
	protected String suppliertel;

	/** 
	 * This attribute maps to the column SUPPLIERTAX in the K_SUPPLIER table.
	 */
	protected String suppliertax;

	/** 
	 * This attribute maps to the column USERNAME in the K_SUPPLIER table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column USERTEL in the K_SUPPLIER table.
	 */
	protected String usertel;

	/** 
	 * This attribute maps to the column REMARK in the K_SUPPLIER table.
	 */
	protected String remark;

	/**
	 * Method 'KSupplier'
	 * 
	 */
	public KSupplier()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getSupplierno'
	 * 
	 * @return String
	 */
	public String getSupplierno()
	{
		return supplierno;
	}

	/**
	 * Method 'setSupplierno'
	 * 
	 * @param supplierno
	 */
	public void setSupplierno(String supplierno)
	{
		this.supplierno = supplierno;
	}

	/**
	 * Method 'getSuppliername'
	 * 
	 * @return String
	 */
	public String getSuppliername()
	{
		return suppliername;
	}

	/**
	 * Method 'setSuppliername'
	 * 
	 * @param suppliername
	 */
	public void setSuppliername(String suppliername)
	{
		this.suppliername = suppliername;
	}

	/**
	 * Method 'getProvincecode'
	 * 
	 * @return String
	 */
	public String getProvincecode()
	{
		return provincecode;
	}

	/**
	 * Method 'setProvincecode'
	 * 
	 * @param provincecode
	 */
	public void setProvincecode(String provincecode)
	{
		this.provincecode = provincecode;
	}

	/**
	 * Method 'getSupplieraddress'
	 * 
	 * @return String
	 */
	public String getSupplieraddress()
	{
		return supplieraddress;
	}

	/**
	 * Method 'setSupplieraddress'
	 * 
	 * @param supplieraddress
	 */
	public void setSupplieraddress(String supplieraddress)
	{
		this.supplieraddress = supplieraddress;
	}

	/**
	 * Method 'getSupplieremail'
	 * 
	 * @return String
	 */
	public String getSupplieremail()
	{
		return supplieremail;
	}

	/**
	 * Method 'setSupplieremail'
	 * 
	 * @param supplieremail
	 */
	public void setSupplieremail(String supplieremail)
	{
		this.supplieremail = supplieremail;
	}

	/**
	 * Method 'getSuppliertel'
	 * 
	 * @return String
	 */
	public String getSuppliertel()
	{
		return suppliertel;
	}

	/**
	 * Method 'setSuppliertel'
	 * 
	 * @param suppliertel
	 */
	public void setSuppliertel(String suppliertel)
	{
		this.suppliertel = suppliertel;
	}

	/**
	 * Method 'getSuppliertax'
	 * 
	 * @return String
	 */
	public String getSuppliertax()
	{
		return suppliertax;
	}

	/**
	 * Method 'setSuppliertax'
	 * 
	 * @param suppliertax
	 */
	public void setSuppliertax(String suppliertax)
	{
		this.suppliertax = suppliertax;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getUsertel'
	 * 
	 * @return String
	 */
	public String getUsertel()
	{
		return usertel;
	}

	/**
	 * Method 'setUsertel'
	 * 
	 * @param usertel
	 */
	public void setUsertel(String usertel)
	{
		this.usertel = usertel;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KSupplier)) {
			return false;
		}
		
		final KSupplier _cast = (KSupplier) _other;
		if (id == null ? _cast.id != id : !id.equals( _cast.id )) {
			return false;
		}
		
		if (supplierno == null ? _cast.supplierno != supplierno : !supplierno.equals( _cast.supplierno )) {
			return false;
		}
		
		if (suppliername == null ? _cast.suppliername != suppliername : !suppliername.equals( _cast.suppliername )) {
			return false;
		}
		
		if (provincecode == null ? _cast.provincecode != provincecode : !provincecode.equals( _cast.provincecode )) {
			return false;
		}
		
		if (supplieraddress == null ? _cast.supplieraddress != supplieraddress : !supplieraddress.equals( _cast.supplieraddress )) {
			return false;
		}
		
		if (supplieremail == null ? _cast.supplieremail != supplieremail : !supplieremail.equals( _cast.supplieremail )) {
			return false;
		}
		
		if (suppliertel == null ? _cast.suppliertel != suppliertel : !suppliertel.equals( _cast.suppliertel )) {
			return false;
		}
		
		if (suppliertax == null ? _cast.suppliertax != suppliertax : !suppliertax.equals( _cast.suppliertax )) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (usertel == null ? _cast.usertel != usertel : !usertel.equals( _cast.usertel )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (id != null) {
			_hashCode = 29 * _hashCode + id.hashCode();
		}
		
		if (supplierno != null) {
			_hashCode = 29 * _hashCode + supplierno.hashCode();
		}
		
		if (suppliername != null) {
			_hashCode = 29 * _hashCode + suppliername.hashCode();
		}
		
		if (provincecode != null) {
			_hashCode = 29 * _hashCode + provincecode.hashCode();
		}
		
		if (supplieraddress != null) {
			_hashCode = 29 * _hashCode + supplieraddress.hashCode();
		}
		
		if (supplieremail != null) {
			_hashCode = 29 * _hashCode + supplieremail.hashCode();
		}
		
		if (suppliertel != null) {
			_hashCode = 29 * _hashCode + suppliertel.hashCode();
		}
		
		if (suppliertax != null) {
			_hashCode = 29 * _hashCode + suppliertax.hashCode();
		}
		
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (usertel != null) {
			_hashCode = 29 * _hashCode + usertel.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}


	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.KSupplier: " );
		ret.append( "id=" + id );
		ret.append( ", supplierno=" + supplierno );
		ret.append( ", suppliername=" + suppliername );
		ret.append( ", provincecode=" + provincecode );
		ret.append( ", supplieraddress=" + supplieraddress );
		ret.append( ", supplieremail=" + supplieremail );
		ret.append( ", suppliertel=" + suppliertel );
		ret.append( ", suppliertax=" + suppliertax );
		ret.append( ", username=" + username );
		ret.append( ", usertel=" + usertel );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
