/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.math.BigDecimal;

public class KUser implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_USER table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column USERNO in the K_USER table.
	 */
	protected String userno;

	/** 
	 * This attribute maps to the column USERNAME in the K_USER table.
	 */
	protected String username;

	/** 
	 * This attribute maps to the column PWD in the K_USER table.
	 */
	protected String pwd;

	/** 
	 * This attribute maps to the column DEPTNO in the K_USER table.
	 */
	protected String deptno;

	/** 
	 * This attribute maps to the column SEX in the K_USER table.
	 */
	protected String sex;

	/** 
	 * This attribute maps to the column AGE in the K_USER table.
	 */
	protected int age;

	/** 
	 * This attribute represents whether the primitive attribute age is null.
	 */
	protected boolean ageNull = true;

	/** 
	 * This attribute maps to the column POSITION in the K_USER table.
	 */
	protected String position;

	/** 
	 * This attribute maps to the column HOMETOWN in the K_USER table.
	 */
	protected String hometown;

	/** 
	 * This attribute maps to the column TELPHONE in the K_USER table.
	 */
	protected String telphone;

	/** 
	 * This attribute maps to the column EMAIL in the K_USER table.
	 */
	protected String email;

	/** 
	 * This attribute maps to the column ROLENO in the K_USER table.
	 */
	protected String roleno;

	/** 
	 * This attribute maps to the column REMARK in the K_USER table.
	 */
	protected String remark;

	/**
	 * Method 'KUser'
	 * 
	 */
	public KUser()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getUserno'
	 * 
	 * @return String
	 */
	public String getUserno()
	{
		return userno;
	}

	/**
	 * Method 'setUserno'
	 * 
	 * @param userno
	 */
	public void setUserno(String userno)
	{
		this.userno = userno;
	}

	/**
	 * Method 'getUsername'
	 * 
	 * @return String
	 */
	public String getUsername()
	{
		return username;
	}

	/**
	 * Method 'setUsername'
	 * 
	 * @param username
	 */
	public void setUsername(String username)
	{
		this.username = username;
	}

	/**
	 * Method 'getPwd'
	 * 
	 * @return String
	 */
	public String getPwd()
	{
		return pwd;
	}

	/**
	 * Method 'setPwd'
	 * 
	 * @param pwd
	 */
	public void setPwd(String pwd)
	{
		this.pwd = pwd;
	}

	/**
	 * Method 'getDeptno'
	 * 
	 * @return String
	 */
	public String getDeptno()
	{
		return deptno;
	}

	/**
	 * Method 'setDeptno'
	 * 
	 * @param deptno
	 */
	public void setDeptno(String deptno)
	{
		this.deptno = deptno;
	}

	/**
	 * Method 'getSex'
	 * 
	 * @return String
	 */
	public String getSex()
	{
		return sex;
	}

	/**
	 * Method 'setSex'
	 * 
	 * @param sex
	 */
	public void setSex(String sex)
	{
		this.sex = sex;
	}

	/**
	 * Method 'getAge'
	 * 
	 * @return int
	 */
	public int getAge()
	{
		return age;
	}

	/**
	 * Method 'setAge'
	 * 
	 * @param age
	 */
	public void setAge(int age)
	{
		this.age = age;
		this.ageNull = false;
	}

	/**
	 * Method 'setAgeNull'
	 * 
	 * @param value
	 */
	public void setAgeNull(boolean value)
	{
		this.ageNull = value;
	}

	/**
	 * Method 'isAgeNull'
	 * 
	 * @return boolean
	 */
	public boolean isAgeNull()
	{
		return ageNull;
	}

	/**
	 * Method 'getPosition'
	 * 
	 * @return String
	 */
	public String getPosition()
	{
		return position;
	}

	/**
	 * Method 'setPosition'
	 * 
	 * @param position
	 */
	public void setPosition(String position)
	{
		this.position = position;
	}

	/**
	 * Method 'getHometown'
	 * 
	 * @return String
	 */
	public String getHometown()
	{
		return hometown;
	}

	/**
	 * Method 'setHometown'
	 * 
	 * @param hometown
	 */
	public void setHometown(String hometown)
	{
		this.hometown = hometown;
	}

	/**
	 * Method 'getTelphone'
	 * 
	 * @return String
	 */
	public String getTelphone()
	{
		return telphone;
	}

	/**
	 * Method 'setTelphone'
	 * 
	 * @param telphone
	 */
	public void setTelphone(String telphone)
	{
		this.telphone = telphone;
	}

	/**
	 * Method 'getEmail'
	 * 
	 * @return String
	 */
	public String getEmail()
	{
		return email;
	}

	/**
	 * Method 'setEmail'
	 * 
	 * @param email
	 */
	public void setEmail(String email)
	{
		this.email = email;
	}

	/**
	 * Method 'getRoleno'
	 * 
	 * @return String
	 */
	public String getRoleno()
	{
		return roleno;
	}

	/**
	 * Method 'setRoleno'
	 * 
	 * @param roleno
	 */
	public void setRoleno(String roleno)
	{
		this.roleno = roleno;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KUser)) {
			return false;
		}
		
		final KUser _cast = (KUser) _other;
		if (id == null ? _cast.id != id : !id.equals( _cast.id )) {
			return false;
		}
		
		if (userno == null ? _cast.userno != userno : !userno.equals( _cast.userno )) {
			return false;
		}
		
		if (username == null ? _cast.username != username : !username.equals( _cast.username )) {
			return false;
		}
		
		if (pwd == null ? _cast.pwd != pwd : !pwd.equals( _cast.pwd )) {
			return false;
		}
		
		if (deptno == null ? _cast.deptno != deptno : !deptno.equals( _cast.deptno )) {
			return false;
		}
		
		if (sex == null ? _cast.sex != sex : !sex.equals( _cast.sex )) {
			return false;
		}
		
		if (age != _cast.age) {
			return false;
		}
		
		if (ageNull != _cast.ageNull) {
			return false;
		}
		
		if (position == null ? _cast.position != position : !position.equals( _cast.position )) {
			return false;
		}
		
		if (hometown == null ? _cast.hometown != hometown : !hometown.equals( _cast.hometown )) {
			return false;
		}
		
		if (telphone == null ? _cast.telphone != telphone : !telphone.equals( _cast.telphone )) {
			return false;
		}
		
		if (email == null ? _cast.email != email : !email.equals( _cast.email )) {
			return false;
		}
		
		if (roleno == null ? _cast.roleno != roleno : !roleno.equals( _cast.roleno )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (id != null) {
			_hashCode = 29 * _hashCode + id.hashCode();
		}
		
		if (userno != null) {
			_hashCode = 29 * _hashCode + userno.hashCode();
		}
		
		if (username != null) {
			_hashCode = 29 * _hashCode + username.hashCode();
		}
		
		if (pwd != null) {
			_hashCode = 29 * _hashCode + pwd.hashCode();
		}
		
		if (deptno != null) {
			_hashCode = 29 * _hashCode + deptno.hashCode();
		}
		
		if (sex != null) {
			_hashCode = 29 * _hashCode + sex.hashCode();
		}
		
		_hashCode = 29 * _hashCode + age;
		_hashCode = 29 * _hashCode + (ageNull ? 1 : 0);
		if (position != null) {
			_hashCode = 29 * _hashCode + position.hashCode();
		}
		
		if (hometown != null) {
			_hashCode = 29 * _hashCode + hometown.hashCode();
		}
		
		if (telphone != null) {
			_hashCode = 29 * _hashCode + telphone.hashCode();
		}
		
		if (email != null) {
			_hashCode = 29 * _hashCode + email.hashCode();
		}
		
		if (roleno != null) {
			_hashCode = 29 * _hashCode + roleno.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "KUser: " );
		ret.append( "id=" + id );
		ret.append( ", userno=" + userno );
		ret.append( ", username=" + username );
		ret.append( ", pwd=" + pwd );
		ret.append( ", deptno=" + deptno );
		ret.append( ", sex=" + sex );
		ret.append( ", age=" + age );
		ret.append( ", position=" + position );
		ret.append( ", hometown=" + hometown );
		ret.append( ", telphone=" + telphone );
		ret.append( ", email=" + email );
		ret.append( ", roleno=" + roleno );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
