/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.GoodsDaoI;
import com.hyg.dao.impl.GoodsDaoImpl;

public class GoodsDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return GoodsDaoI
	 */
	public static GoodsDaoI create()
	{
		return new GoodsDaoImpl();
	}

}
