/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.InstockDetailDaoI;
import com.hyg.dao.impl.InstockDetailDaoImpl;

public class InstockDetailDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return InstockDetailDaoI
	 */
	public static InstockDetailDaoI create()
	{
		return new InstockDetailDaoImpl();
	}


}
