/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.OutstockDetailDaoI;
import com.hyg.dao.impl.OutstockDetailDaoImpl;


public class OutstockDetailDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return OutstockDetailDaoI
	 */
	public static OutstockDetailDaoI create()
	{
		return new OutstockDetailDaoImpl();
	}

}
