/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import java.sql.Connection;

import com.hyg.dao.StockDaoI;
import com.hyg.dao.impl.StockDaoImpl;

public class StockDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return StockDaoI
	 */
	public static StockDaoI create()
	{
		return new StockDaoImpl();
	}

}
