/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.SupplierDaoI;
import com.hyg.dao.impl.SupplierDaoImpl;

public class SupplierDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return SupplierDaoI
	 */
	public static SupplierDaoI create()
	{
		return new SupplierDaoImpl();
	}

}
