/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.UserDaoI;
import com.hyg.dao.impl.UserDaoImpl;

public class UserDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return UserDaoI
	 */
	public static UserDaoI create()
	{
		return new UserDaoImpl();
	}

}
