/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import java.sql.Connection;

import com.hyg.dao.DeptDaoI;
import com.hyg.dao.impl.DeptDaoImpl;

/**
 * @author 黑猴子的家
 * @博客 https://www.jianshu.com/u/37fd8e2dff4c
 * @官网 http://www.121ugrow.com/
 */
public class DeptDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return DeptDaoI
	 */
	public static DeptDaoI create()
	{
		return new DeptDaoImpl();
	}

	/**
	 * Method 'create'
	 * 
	 * @param conn
	 * @return DeptDaoI
	 */
	public static DeptDaoI create(Connection conn)
	{
		return new DeptDaoImpl( conn );
	}

}
