/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.factory;

import com.hyg.dao.OutstockDetailDaoI;
import com.hyg.dao.impl.OutstockDetailDaoImpl;

/**
 * @author 黑猴子的家
 * @博客 https://www.jianshu.com/u/37fd8e2dff4c
 * @官网 http://www.121ugrow.com/
 */
public class OutstockDetailDaoFactory
{
	/**
	 * Method 'create'
	 * 
	 * @return OutstockDetailDaoI
	 */
	public static OutstockDetailDaoI create()
	{
		return new OutstockDetailDaoImpl();
	}

}
