/*
 * This source file was generated by FireStorm/DAO.
 * 
 * If you purchase a full license for FireStorm/DAO you can customize this header file.
 * 
 * For more information please visit http://www.codefutures.com/products/firestorm
 */

package com.hyg.model;

import java.io.Serializable;
import java.util.*;
import java.math.BigDecimal;
/**
 * @author 黑猴子的家
 * @博客 https://www.jianshu.com/u/37fd8e2dff4c
 * @官网 http://www.121ugrow.com/
 */
public class KDept implements Serializable
{
	/** 
	 * This attribute maps to the column ID in the K_DEPT table.
	 */
	protected BigDecimal id;

	/** 
	 * This attribute maps to the column DEPTNO in the K_DEPT table.
	 */
	protected String deptno;

	/** 
	 * This attribute maps to the column DEPTNAME in the K_DEPT table.
	 */
	protected String deptname;

	/** 
	 * This attribute maps to the column DEPTLEADER in the K_DEPT table.
	 */
	protected String deptleader;

	/** 
	 * This attribute maps to the column DEPTTEL in the K_DEPT table.
	 */
	protected String depttel;

	/** 
	 * This attribute maps to the column PARENTDEPTNO in the K_DEPT table.
	 */
	protected String parentdeptno;

	/** 
	 * This attribute maps to the column DEPTDESC in the K_DEPT table.
	 */
	protected String deptdesc;

	/** 
	 * This attribute maps to the column REMARK in the K_DEPT table.
	 */
	protected String remark;

	/**
	 * Method 'KDept'
	 * 
	 */
	public KDept()
	{
	}

	/**
	 * Method 'getId'
	 * 
	 * @return BigDecimal
	 */
	public BigDecimal getId()
	{
		return id;
	}

	/**
	 * Method 'setId'
	 * 
	 * @param id
	 */
	public void setId(BigDecimal id)
	{
		this.id = id;
	}

	/**
	 * Method 'getDeptno'
	 * 
	 * @return String
	 */
	public String getDeptno()
	{
		return deptno;
	}

	/**
	 * Method 'setDeptno'
	 * 
	 * @param deptno
	 */
	public void setDeptno(String deptno)
	{
		this.deptno = deptno;
	}

	/**
	 * Method 'getDeptname'
	 * 
	 * @return String
	 */
	public String getDeptname()
	{
		return deptname;
	}

	/**
	 * Method 'setDeptname'
	 * 
	 * @param deptname
	 */
	public void setDeptname(String deptname)
	{
		this.deptname = deptname;
	}

	/**
	 * Method 'getDeptleader'
	 * 
	 * @return String
	 */
	public String getDeptleader()
	{
		return deptleader;
	}

	/**
	 * Method 'setDeptleader'
	 * 
	 * @param deptleader
	 */
	public void setDeptleader(String deptleader)
	{
		this.deptleader = deptleader;
	}

	/**
	 * Method 'getDepttel'
	 * 
	 * @return String
	 */
	public String getDepttel()
	{
		return depttel;
	}

	/**
	 * Method 'setDepttel'
	 * 
	 * @param depttel
	 */
	public void setDepttel(String depttel)
	{
		this.depttel = depttel;
	}

	/**
	 * Method 'getParentdeptno'
	 * 
	 * @return String
	 */
	public String getParentdeptno()
	{
		return parentdeptno;
	}

	/**
	 * Method 'setParentdeptno'
	 * 
	 * @param parentdeptno
	 */
	public void setParentdeptno(String parentdeptno)
	{
		this.parentdeptno = parentdeptno;
	}

	/**
	 * Method 'getDeptdesc'
	 * 
	 * @return String
	 */
	public String getDeptdesc()
	{
		return deptdesc;
	}

	/**
	 * Method 'setDeptdesc'
	 * 
	 * @param deptdesc
	 */
	public void setDeptdesc(String deptdesc)
	{
		this.deptdesc = deptdesc;
	}

	/**
	 * Method 'getRemark'
	 * 
	 * @return String
	 */
	public String getRemark()
	{
		return remark;
	}

	/**
	 * Method 'setRemark'
	 * 
	 * @param remark
	 */
	public void setRemark(String remark)
	{
		this.remark = remark;
	}

	/**
	 * Method 'equals'
	 * 
	 * @param _other
	 * @return boolean
	 */
	public boolean equals(Object _other)
	{
		if (_other == null) {
			return false;
		}
		
		if (_other == this) {
			return true;
		}
		
		if (!(_other instanceof KDept)) {
			return false;
		}
		
		final KDept _cast = (KDept) _other;
		if (id == null ? _cast.id != id : !id.equals( _cast.id )) {
			return false;
		}
		
		if (deptno == null ? _cast.deptno != deptno : !deptno.equals( _cast.deptno )) {
			return false;
		}
		
		if (deptname == null ? _cast.deptname != deptname : !deptname.equals( _cast.deptname )) {
			return false;
		}
		
		if (deptleader == null ? _cast.deptleader != deptleader : !deptleader.equals( _cast.deptleader )) {
			return false;
		}
		
		if (depttel == null ? _cast.depttel != depttel : !depttel.equals( _cast.depttel )) {
			return false;
		}
		
		if (parentdeptno == null ? _cast.parentdeptno != parentdeptno : !parentdeptno.equals( _cast.parentdeptno )) {
			return false;
		}
		
		if (deptdesc == null ? _cast.deptdesc != deptdesc : !deptdesc.equals( _cast.deptdesc )) {
			return false;
		}
		
		if (remark == null ? _cast.remark != remark : !remark.equals( _cast.remark )) {
			return false;
		}
		
		return true;
	}

	/**
	 * Method 'hashCode'
	 * 
	 * @return int
	 */
	public int hashCode()
	{
		int _hashCode = 0;
		if (id != null) {
			_hashCode = 29 * _hashCode + id.hashCode();
		}
		
		if (deptno != null) {
			_hashCode = 29 * _hashCode + deptno.hashCode();
		}
		
		if (deptname != null) {
			_hashCode = 29 * _hashCode + deptname.hashCode();
		}
		
		if (deptleader != null) {
			_hashCode = 29 * _hashCode + deptleader.hashCode();
		}
		
		if (depttel != null) {
			_hashCode = 29 * _hashCode + depttel.hashCode();
		}
		
		if (parentdeptno != null) {
			_hashCode = 29 * _hashCode + parentdeptno.hashCode();
		}
		
		if (deptdesc != null) {
			_hashCode = 29 * _hashCode + deptdesc.hashCode();
		}
		
		if (remark != null) {
			_hashCode = 29 * _hashCode + remark.hashCode();
		}
		
		return _hashCode;
	}

	/**
	 * Method 'toString'
	 * 
	 * @return String
	 */
	public String toString()
	{
		StringBuffer ret = new StringBuffer();
		ret.append( "com.mycompany.myapp.dto.KDept: " );
		ret.append( "id=" + id );
		ret.append( ", deptno=" + deptno );
		ret.append( ", deptname=" + deptname );
		ret.append( ", deptleader=" + deptleader );
		ret.append( ", depttel=" + depttel );
		ret.append( ", parentdeptno=" + parentdeptno );
		ret.append( ", deptdesc=" + deptdesc );
		ret.append( ", remark=" + remark );
		return ret.toString();
	}

}
